### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by b-jerome** [soflyy/wp-all-import-example-addon#3]
Hello,

I tried to use this Addon but got a fatal error with wp-all-import-pro 4.6.3 / wordpress 5.4.2 :

[27-Aug-2020 16:53:21 UTC] PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'Yoast_SEO_Add_On' does not have a method 'get_default_import_options' in /wp-content/plugins/wp-all-import-pro/controllers/admin/import.php on line 1478
[27-Aug-2020 16:53:21 UTC] PHP Fatal error:  Uncaught Error: Unsupported operand types in /wp-content/plugins/wp-all-import-pro/controllers/admin/import.php:1478
Stack trace:
#0 /wp-content/plugins/wp-all-import-pro/wp-all-import-pro.php(732): PMXI_Admin_Import->template()
#1 /wp-includes/class-wp-hook.php(287): PMXI_Plugin->adminInit()
#2 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#3 /wp-includes/plugin.php(478): WP_Hook->do_action()
#4 /wp-admin/admin.php(170): do_action()
#5 {main}
  thrown in /wp-content/plugins/wp-all-import-pro/controllers/admin/import.php on line 1478

**Comment by trey8611** [comment]
Hey @b-jerome,

Thanks for the heads up. I pushed a fix for this.
